### ISSUE TITLE
Minification breaks certain selectors

### ISSUE THREAD

**Issue by jroessel** [kamgru/kaskada-minify#1]
e.g.

        [Fact]
        public void Minify_ShouldNotRemoveWhitespaceBetweenParenthesisAndClassSelector() =>
            AssertResultAsExpected(
                ".foo:not(:hover) .bar {}",
                ".foo:not(:hover) .bar{}");

In this case the space after the `)` is significant and must not be removed; otherwise the selector matches something else entirely.

I tried finding a good place to fix this in Minifier.cs, but the code doesn't event really know the context of where the cursor currently is and whether it's in a selector or a declaration.

**Comment by kamgru** [comment]
Hi @jroessel, thanks for the feedback. Could you provide an example of a selector that gets broken by the minifier?

**Comment by jroessel** [comment]
I've even included a test case above ;-)

```
.foo:not(:hover) .bar {}
```

gets currently shortened to

```
.foo:not(:hover).bar{}
```

which unexpectedly drops the descendant combinator.

**Comment by kamgru** [comment]
Ah, I see, thanks, will look into it.

**Comment by kamgru** [comment]
@jroessel There's a new version available, that fixes this issue. I have included the test case you provided.

`
dotnet add package Kaskada.Minify --version 1.1.3
`

**Comment by jroessel** [comment]
Hey, thanks a lot for the quick response.
